required-player-count : 2
return-to-lobby-delay : 10
respawn-delay : 7
spawn-protection-distance : 6

time-to-first-phase : 60
time-to-second-phase : 120
time-to-bed-destruction-phase : 300
time-to-sudden-death-phase : 360

random-teams: true

armor : ["LEATHER_BOOTS", "LEATHER_LEGGINGS", "LEATHER_CHESTPLATE", "LEATHER_HELMET"]
hotbar :
  WOODEN_SWORD: 1