required-player-count : 1
return-to-lobby-delay : 10
respawn-delay : 7
spawn-protection-distance : 6


armor : ["LEATHER_BOOTS", "LEATHER_LEGGINGS", "LEATHER_CHESTPLATE", "LEATHER_HELMET"]
hotbar :
  WOODEN_SWORD: 1